"""
Realtime waveform -> fingerprint -> LSH matching

- Ingest 1-second (or arbitrary short) frames from wfdisc/CSS streams
- Build FAST fingerprints every fp_window seconds with fp_stride spacing
- Cache template fingerprints, hash them with a light-weight LSH, and
  emit matches or "hot" buckets whose occupancy exceeds a threshold.

Example wiring with a 1-second frame pull:
    params = load_params("path/to/fp_params.json")
    processor = RealtimeWaveformProcessor(params,
        template_fingerprints=template_bytes_list,
        template_ids=template_ids,
        fp_stride=1.0,
        fp_window=8.0)
    for frame_data, frame_start in stream_generator():
        hits = processor.ingest_frame(frame_data, frame_start)
        for hit in hits:
            print(hit)
"""

import datetime
import hashlib
from collections import defaultdict, deque
from dataclasses import dataclass
from typing import Deque, Dict, Iterable, List, Optional, Tuple

import numpy as np

from config import (get_min_fp_length, get_ntimes, get_partition_padding,
	gen_mad_fname, parse_json)
from finger_print import compute_fingerprint_block, load_mad_stats
from feature_extractor import init_feature_extractor


@dataclass
class FingerprintHit:
	fp_time: datetime.datetime
	matched_templates: List[str]
	hot_buckets: List[Tuple[int, str]]


class SimpleLSH:
	"""
	A light-weight LSH implementation tailored for the binary fingerprints
	generated by FAST. It hashes each fingerprint into multiple bands and
	reports matches against:
	  1) preloaded template fingerprints
	  2) buckets whose occupancy exceeds a configured threshold
	"""
	def __init__(self, num_bands: int = 16, rows_per_band: int = 8,
		bucket_threshold: int = 3):
		self.num_bands = num_bands
		self.rows_per_band = rows_per_band
		self.bucket_threshold = bucket_threshold
		self.template_buckets: Dict[Tuple[int, str], List[str]] = defaultdict(list)
		self.bucket_counts: Dict[Tuple[int, str], int] = defaultdict(int)

	def _hash(self, fp_bytes: bytes) -> Iterable[Tuple[int, str]]:
		bits = np.unpackbits(np.frombuffer(fp_bytes, dtype=np.uint8))
		band_size = self.rows_per_band
		for band in range(self.num_bands):
			start = band * band_size
			if start >= bits.size:
				break
			end = min(start + band_size, bits.size)
			segment = bits[start:end]
			segment_bytes = np.packbits(segment).tobytes()
			bucket_key = hashlib.sha1(segment_bytes).hexdigest()[:16]
			yield band, bucket_key

	def add_template(self, fp_bytes: bytes, template_id: str) -> None:
		for band, key in self._hash(fp_bytes):
			self.template_buckets[(band, key)].append(template_id)

	def record(self, fp_bytes: bytes) -> Tuple[List[str], List[Tuple[int, str]]]:
		matches = set()
		hot_buckets: List[Tuple[int, str]] = []
		for band, key in self._hash(fp_bytes):
			bucket_key = (band, key)
			self.bucket_counts[bucket_key] += 1
			if self.bucket_counts[bucket_key] >= self.bucket_threshold:
				hot_buckets.append(bucket_key)
			matches.update(self.template_buckets.get(bucket_key, []))
		return list(matches), hot_buckets


class FingerprintGenerator:
	def __init__(self, params: dict):
		self.params = params
		self.ntimes = get_ntimes(params)
		self.feats = init_feature_extractor(params, self.ntimes)
		load_mad_stats(gen_mad_fname(params), params, self.feats)
		self.partition_padding = get_partition_padding(params).total_seconds()

	def generate(self, window_data: np.ndarray, window_start: datetime.datetime):
		return compute_fingerprint_block(window_data, window_start, self.params, self.feats)


class RingBuffer:
	def __init__(self, sampling_rate: float, max_seconds: float):
		self.sampling_rate = sampling_rate
		self.max_samples = int(max_seconds * sampling_rate)
		self.data = np.empty(0, dtype=np.float64)
		self.start_time: Optional[datetime.datetime] = None

	def append(self, samples: np.ndarray, start_time: datetime.datetime) -> None:
		if self.start_time is None:
			self.start_time = start_time
		self.data = np.concatenate([self.data, samples])
		self._truncate()

	def _truncate(self) -> None:
		if self.data.size > self.max_samples:
			drop = self.data.size - self.max_samples
			if drop > 0:
				self.data = self.data[drop:]
				self.start_time = self.start_time + datetime.timedelta(
					seconds = drop / self.sampling_rate)

	def window(self, window_start: datetime.datetime, window_seconds: float
		) -> Optional[np.ndarray]:
		if self.start_time is None:
			return None
		offset_start = (window_start - self.start_time).total_seconds()
		offset_end = offset_start + window_seconds
		if offset_start < 0:
			return None
		if offset_end > self.data.size / self.sampling_rate:
			return None
		idx_start = int(offset_start * self.sampling_rate)
		idx_end = int(offset_end * self.sampling_rate)
		return self.data[idx_start:idx_end].copy()

	@property
	def end_time(self) -> Optional[datetime.datetime]:
		if self.start_time is None:
			return None
		return self.start_time + datetime.timedelta(
			seconds = self.data.size / self.sampling_rate)

	def trim_before(self, keep_from: datetime.datetime) -> None:
		if self.start_time is None:
			return
		if keep_from <= self.start_time:
			return
		offset = (keep_from - self.start_time).total_seconds()
		if offset <= 0:
			return
		drop = int(offset * self.sampling_rate)
		if drop > 0 and drop < self.data.size:
			self.data = self.data[drop:]
			self.start_time = keep_from


class RealtimeWaveformProcessor:
	"""
	Realtime orchestrator:
	- ingest 1-second frames (or any short frames) from wfdisc/CSS reads
	- generate fingerprints every fp_stride seconds once enough data is buffered
	- run LSH matching against template fingerprints and hot buckets
	"""
	def __init__(self, params: dict, template_fingerprints: Optional[List[bytes]] = None,
		template_ids: Optional[List[str]] = None, buffer_seconds: float = 3600,
		fp_stride: float = 1.0, fp_window: Optional[float] = None,
		lsh_bands: int = 16, lsh_rows: int = 8, bucket_threshold: int = 3,
		cache_size: int = 10000):
		self.params = params
		self.sampling_rate = params['fingerprint']['sampling_rate']
		self.fp_window = fp_window or params['performance']['partition_len']
		self.fp_stride = fp_stride
		self.fp_padding = get_partition_padding(params).total_seconds()
		self.fp_min = get_min_fp_length(params)

		self.buffer = RingBuffer(self.sampling_rate, buffer_seconds)
		self.generator = FingerprintGenerator(params)
		self.lsh = SimpleLSH(num_bands = lsh_bands, rows_per_band = lsh_rows,
			bucket_threshold = bucket_threshold)
		self.cache: Deque[Tuple[List[datetime.datetime], List[bytes]]] = deque(maxlen = cache_size)
		self.next_fp_time: Optional[datetime.datetime] = None

		if template_fingerprints:
			for idx, fp_bytes in enumerate(template_fingerprints):
				template_id = template_ids[idx] if template_ids and idx < len(template_ids) else f"template_{idx}"
				self.lsh.add_template(fp_bytes, template_id)

	def _to_datetime(self, ts) -> datetime.datetime:
		if isinstance(ts, datetime.datetime):
			return ts
		return datetime.datetime.utcfromtimestamp(ts)

	def ingest_frame(self, frame: np.ndarray, frame_start: datetime.datetime
		) -> List[FingerprintHit]:
		frame_start_dt = self._to_datetime(frame_start)
		self.buffer.append(frame, frame_start_dt)
		if self.next_fp_time is None:
			self.next_fp_time = frame_start_dt

		hits: List[FingerprintHit] = []
		window_seconds = self.fp_window + self.fp_padding

		while True:
			window_data = self.buffer.window(self.next_fp_time, window_seconds)
			if window_data is None:
				break
			fp_times, fp_bytes_list = self.generator.generate(
				window_data, self.next_fp_time)
			self.cache.append((fp_times, fp_bytes_list))
			for ts, fp_bytes in zip(fp_times, fp_bytes_list):
				matched_templates, hot_buckets = self.lsh.record(fp_bytes)
				if matched_templates or hot_buckets:
					hits.append(FingerprintHit(
						fp_time = ts,
						matched_templates = matched_templates,
						hot_buckets = hot_buckets))
			self.next_fp_time = self.next_fp_time + datetime.timedelta(seconds = self.fp_stride)

		trim_point = self.next_fp_time - datetime.timedelta(seconds = self.fp_padding)
		self.buffer.trim_before(trim_point)
		return hits


def load_params(param_path: str) -> dict:
	params = parse_json(param_path)
	return params
